HabitAqui/HabitAqui/Models/Manager.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HabitAqui.Models
{
    public class Manager
    {
        public int ManagerId { get; set; }

        public ApplicationUser ApplicationUser { get; set; }


        // tem uma lista de empregados
        public ICollection<Employee> Employees { get; set; }

        // tem uma lista de alojamentos
        public ICollection<Accomodation> Accomodations { get; set; }
    }
}

HabitAqui/HabitAqui/Controllers/AccomodationController.cs
using HabitAqui.Data;
using HabitAqui.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace HabitAqui.Controllers
{
    public class AccomodationController : Controller
    {
        private readonly ApplicationDbContext _context;

        public AccomodationController(ApplicationDbContext context)
        {
            _context = context;
        }

        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var accomodation = _context.Accomodations.Include(x => x.AccomodationImages);
            return View(await accomodation.ToListAsync());
        }

        [AllowAnonymous]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var accomodation = await _context.Accomodations
                .Include(e => e.Category)
                .Include(x => x.AccomodationImages)
                .Include(y => y.AccomodationRatings).ThenInclude(c => c.Customer)
                .FirstOrDefaultAsync(m => m.AccomodationId == id);
            if (accomodation == null)
            {
                return NotFound();
            }

            return View(accomodation);
        }
        

        [Authorize(Roles = "Admin, Manager")]
        // GET: Accomodation/Create
        public IActionResult Create()
        {
            ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "Name");
            return View();
        }

        // POST: Accomodation/Create
        [Authorize(Roles = "Admin, Manager")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("AccomodationId,Name,Description,Location,AvailableFrom,AvailableUntil,PricePerNight,CategoryId")] Accomodation accomodation, List<IFormFile> files)
        {
            // atribui alojamento a um manager
            var applicationUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var manager = _context.Managers.Where(x => x.ApplicationUser.Id == applicationUserId).First();
            accomodation.ManagerId = manager.ManagerId;


            if (ModelState.IsValid)
            {
                
                _context.Add(accomodation);

                foreach (var file in files)
                {
                    var fileName = Path.GetFileNameWithoutExtension(file.FileName);
                    var extension = Path.GetExtension(file.FileName);
                    var fileModel = new AccomodationImage
                    {
                        Accomodation = accomodation,
                        CreatedOn = DateTime.UtcNow,
                        FileType = file.ContentType,
                        Extension = extension,
                        Name = fileName,
                    };
                    using (var dataStream = new MemoryStream())
                    {
                        await file.CopyToAsync(dataStream);
                        fileModel.Data = dataStream.ToArray();
                    }
                    _context.AccomodationImages.Add(fileModel);
                }
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }



            ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "Name", accomodation.CategoryId);

            return View(accomodation);
        }

        [Authorize(Roles = "Admin, Manager")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var accomodation = await _context.Accomodations.FindAsync(id);
            if (accomodation == null)
            {
                return NotFound();
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "Name", accomodation.CategoryId);
            return View(accomodation);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin, Manager")]
        public async Task<IActionResult> Edit(int id, [Bind("AccomodationId,Name,Description,Location,AvailableFrom,AvailableUntil,PricePerNight,CategoryId,ManagerId")] Accomodation accomodation, List<IFormFile> files)
        {
            if (id != accomodation.AccomodationId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {

                    foreach (var file in files)
                    {
                        var fileName = Path.GetFileNameWithoutExtension(file.FileName);
                        var extension = Path.GetExtension(file.FileName);
                        var fileModel = new AccomodationImage
                        {
                            Accomodation = accomodation,
                            CreatedOn = DateTime.UtcNow,
                            FileType = file.ContentType,
                            Extension = extension,
                            Name = fileName,
                        };
                        using (var dataStream = new MemoryStream())
                        {
                            await file.CopyToAsync(dataStream);
                            fileModel.Data = dataStream.ToArray();
                        }
                        _context.AccomodationImages.Add(fileModel);
                    }

                    _context.Update(accomodation);
                    await _context.SaveChangesAsync();
                    
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AccomodationExists(accomodation.AccomodationId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "Name", accomodation.CategoryId);
            return View(accomodation);
        }


        [Authorize(Roles = "Admin, Manager")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var accomodation = await _context.Accomodations
                .Include(p => p.Category)
                .FirstOrDefaultAsync(m => m.AccomodationId == id);
            if (accomodation == null)
            {
                return NotFound();
            }

            return View(accomodation);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin, Manager")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var accomodation = await _context.Accomodations.FindAsync(id);
            _context.Accomodations.Remove(accomodation);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        // checks if accomodation exists in db
        private bool AccomodationExists(int id)
        {
            return _context.Accomodations.Any(e => e.AccomodationId == id);
        }

    }
}

HabitAqui/HabitAqui/Controllers/EmployeesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HabitAqui.Data;
using HabitAqui.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Security.Claims;

namespace HabitAqui.Controllers
{
    [Authorize(Roles = "Admin, Manager,Employee")]
    public class EmployeesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;


        public EmployeesController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;

        }


        // GET: Employees/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var employee = await _context.Employees
                .Include(e => e.Manager.ApplicationUser)
                .Include(a => a.Bookings).ThenInclude(a => a.Accomodation)
                .Include(a => a.ApplicationUser)
                .Include(a => a.Accomodations)
                .FirstOrDefaultAsync(m => m.EmployeeId == id);
            if (employee == null)
            {
                return NotFound();
            }

            return View(employee);
        }


        // GET: Employees/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var employee = await _context.Employees
                .Include(e => e.ApplicationUser)
                .FirstOrDefaultAsync(m => m.EmployeeId == id);
            if (employee == null)
            {
                return NotFound();
            }

            return View(employee);
        }

        // POST: Employees/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            // coloca o EmployeesFK a nulo no Accomodation
            var acc = await _context.Accomodations.Where(x => x.EmployeeId == id).ToListAsync();
            if (acc.Count != 0)
            {
                foreach (var x in acc)
                    x.EmployeeId = null;
            }

            // pesquisar na tabela de Employees o ApplicationUserId e remove esse empregado
            var app = _context.Employees.Where(x => x.EmployeeId == id).Include(x => x.ApplicationUser).First();
            var appuser = app.ApplicationUser;
            await _userManager.DeleteAsync(appuser);

            // removo o empregado da tabela Employee
            var employee = await _context.Employees.FindAsync(id);
            _context.Employees.Remove(employee);

            await _context.SaveChangesAsync();

            return RedirectToAction("ListEmployees", "Manager");
        }

        private bool EmployeeExists(int id)
        {
            return _context.Employees.Any(e => e.EmployeeId == id);
        }

       [Authorize(Roles = "Employee")]
        public async Task<IActionResult> ManageBookings()
        {
            var applicationUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            var employee = _context.Employees.Where(x => x.ApplicationUser.Id == applicationUserId).FirstOrDefault();

            var acc = _context.Accomodations.Where(x => x.EmployeeId == employee.EmployeeId).FirstOrDefault();

            bool flag = true;

            if (acc == null)
            {
                ViewData["flag"] = false;
                return View();
            }
            else
            {
                ViewData["flag"] = flag;

                var bookings = _context.Bookings.Where(p => p.Employee.EmployeeId == employee.EmployeeId)
                                .Include(b => b.Accomodation)
                                .Include(b => b.Customer)
                                .Include(b => b.Customer.ApplicationUser);

                return View(await bookings.ToListAsync());
            }
                

            
        }

        [Authorize(Roles = "Employee")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ManageBookingsAccept([Bind("BookingId,BookingFrom,BookingUntil,AccomodationId,CustomerId")] Booking booking)
        {
            var applicationUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            var employee = _context.Employees.Where(x => x.ApplicationUser.Id == applicationUserId).FirstOrDefault();

            ViewData["AccomodationId"] = new SelectList(_context.Accomodations, "AccomodationId", "Description", booking.AccomodationId);

            if (String.Compare(booking.Status, "Booking Accepted") != 0)
            {
                booking.Status = "Booking Accepted";
                booking.EmployeeId = employee.EmployeeId;
                _context.Update(booking);
                await _context.SaveChangesAsync();
            }
            return RedirectToAction(nameof(ManageBookings));
        }

        [Authorize(Roles = "Employee")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ManageBookingsRefuse([Bind("BookingId,BookingFrom,BookingUntil,AccomodationId,CustomerId")] Booking booking)
        {
            var applicationUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            var employee = _context.Employees.Where(x => x.ApplicationUser.Id == applicationUserId).FirstOrDefault();

            ViewData["AccomodationId"] = new SelectList(_context.Accomodations, "AccomodationId", "Description", booking.AccomodationId);

            if (String.Compare(booking.Status, "Booking Declined") != 0)
            {
                booking.Status = "Booking Declined";
                booking.EmployeeId = employee.EmployeeId;
                _context.Update(booking);
                await _context.SaveChangesAsync();
            }

            return RedirectToAction(nameof(ManageBookings));
        }
    }
}

HabitAqui/HabitAqui/Views/Manager/Delete.cshtml
@model HabitAqui.Models.Manager

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Manager</h4>
    <hr />
    <dl class="row">
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ManagerId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

HabitAqui/HabitAqui/Views/Manager/EmployeeToAccomodation.cshtml
@model HabitAqui.Models.Accomodation


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="EmployeeToAccomodation">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="AccomodationId" class="control-label"></label>
                <select asp-for="AccomodationId" class="form-control" asp-items="@ViewBag.AccomodationId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Associate Employee" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

HabitAqui/HabitAqui/Views/Manager/ListAccomodations.cshtml
@model List<HabitAqui.Models.Accomodation>

@{
    ViewData["Title"] = "My Accommodations";
}

@if (User.IsInRole("Manager"))
{
    <div class="container-fluid d-flex align-content-end justify-content-end mb-3">
        <a class="btn btn-primary" asp-action="Create" asp-controller="Accomodation">Add new Accommodation</a>
    </div>
}

@foreach (var item in Model)
{
    <div class="card">
        <h5 class="card-header">@item.Name</h5>

        <div class="card-body">
            <div class="d-inline-flex flex-row">
                @foreach (var picture in item.AccomodationImages)
                {
                    <img class="card-img" src="data:@picture.FileType;base64,@Convert.ToBase64String(picture.Data, 0, picture.Data.Length)" alt="test" style="width: 12rem;" />
                    break;
                }

                <div class="container-fluid">
                    <span class="card-text align-text-top">@item.Description</span>
                </div>
            </div>

            <div class="d-flex flex-row justify-content-between">
                <div class="d-flex align-items-center justify-content-between">
                    <span class="mx-3 card-text text-center">Availability:</span>
                    <span class="mx-1 badge badge-primary text-center">@item.AvailableFrom</span>
                    <span class="mx-1 badge badge-primary text-center">@item.AvailableUntil</span>
                </div>
                <div class="row align-items-center">
                    <a class="mx-1 btn btn-primary text-center" asp-controller="Accomodation" asp-action="Details" asp-route-id="@item.AccomodationId">Details</a>
                    @if (User.IsInRole("Admin") || User.IsInRole("Manager"))
                    {
                        <a class="mx-1 btn btn-warning text-center" asp-controller="Accomodation" asp-action="Edit" asp-route-id="@item.AccomodationId">Edit</a>

                        <a class="mx-1 btn btn-danger text-center" asp-controller="Accomodation" asp-action="Delete" asp-route-id="@item.AccomodationId">Delete</a>
                    }
                </div>
            </div>
        </div>
    </div>
    <br />
}

HabitAqui/HabitAqui/Views/Manager/ListEmployees.cshtml
@model List<HabitAqui.Models.Employee>

@{
    ViewData["Title"] = "My Employees";
}

@*<p>
        <a class="btn btn-primary" asp-action="CreateEmployees">Add new Employee</a>
    </p>
*@

<h1>My Employees</h1>

<table class="table">
    <thead>
    <tr>
        <th>
            Employee Id
        </th>
        <th>
            First Name
        </th>
        <th>
            Last Name
        </th>
        <th>
            Email
        </th>
        <th></th>
    </tr>
    </thead>
    <tbody>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(a => item.EmployeeId)
            </td>
            <td>
                @Html.DisplayFor(a => item.ApplicationUser.FirstName)
            </td>
            <td>
                @Html.DisplayFor(a => item.ApplicationUser.LastName)
            </td>
            <td>
                @Html.DisplayFor(a => item.ApplicationUser.Email)
            </td>
            <td>
                <div class="row align-items-center">
                    <a class="mx-1 btn btn-primary text-center" asp-action="Details" asp-controller="Employees" asp-route-id="@item.EmployeeId">Details</a>
                    <a class="mx-1 btn btn-danger text-center" asp-action="Delete" asp-controller="Employees" asp-route-id="@item.EmployeeId">Delete</a>
                </div>
            </td>
        </tr>
    }
    </tbody>
</table>

<div class="container-fluid d-flex align-content-end justify-content-end">
    <a class="btn btn-primary" asp-area="Identity" asp-page="/Account/EmployeeRegister">Register Employee</a>
</div>

HabitAqui/HabitAqui/Views/Manager/RemoveAccomodationFromEmployee.cshtml
@model HabitAqui.Models.Accomodation

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Accomodation</h4>
    <hr />
    <form asp-action="RemoveAccomodationFromEmployee" asp-controller="Manager">
        <input type="hidden" asp-for="AccomodationId" />
        <input type="submit" value="Delete" class="btn btn-danger" />
        <a asp-action="Index">Back to List</a>
    </form>
</div>