HabitAqui/HabitAqui/Controllers/CustomerController.cs
using HabitAqui.Data;
using HabitAqui.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace HabitAqui.Controllers
{
    [Authorize(Roles = "Admin,Customer")]
    public class CustomerController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;


        public CustomerController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;

        }

        public async Task<IActionResult> ListBookings()
        {
            var applicationUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var customer = _context.Customers.Where(x => x.ApplicationUser.Id == applicationUserId).First();

            var bookings = _context.Bookings.Where(p => p.CustomerId == customer.CustomerId);

            return View(await bookings.ToListAsync());
        }

        public async Task<IActionResult> ListRatings()
        {
            var applicationUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var customer = _context.Customers.Where(x => x.ApplicationUser.Id == applicationUserId).First();

            var ratings = _context.AccomodationRatings.Where(p => p.CustomerId == customer.CustomerId);

            return View(await ratings.ToListAsync());
        }

        // GET: Customers/Details/5
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }


            var customer = _context.Customers.Where(x => x.CustomerId == id).Include(a => a.ApplicationUser).First();
            var ratings = _context.AccomodationRatings.Where(p => p.CustomerId == customer.CustomerId);
            var bookings = _context.Bookings.Where(p => p.CustomerId == customer.CustomerId).Include(x => x.Accomodation);

            var viewmodel = new CustomerViewModel
            {
                AccomodationRatings = ratings,
                Customer = customer,
                Bookings = bookings
            };


            if (customer == null)
            {
                return NotFound();
            }

            return View(viewmodel);
        }

        // GET: Customers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var customer = await _context.Customers
                .FirstOrDefaultAsync(m => m.CustomerId == id);
            if (customer == null)
            {
                return NotFound();
            }

            return View(customer);
        }

        // POST: Customers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            // pesquisar na tabela de customers o ApplicationUserId e remove esse customer
            var app = _context.Customers.Where(x => x.CustomerId == id).Include(x => x.ApplicationUser).First();
            var appuser = app.ApplicationUser;
            await _userManager.DeleteAsync(appuser);

            var customer = await _context.Customers.FindAsync(id);
            _context.Customers.Remove(customer);
            await _context.SaveChangesAsync();
            return RedirectToAction("ListCustomers", "Admin");
        }

    }
}

HabitAqui/HabitAqui/Controllers/ManagerController.cs
using HabitAqui.Data;
using HabitAqui.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace HabitAqui.Controllers
{
    [Authorize(Roles = "Admin,Manager,Employee")]
    public class ManagerController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;


        public ManagerController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public async Task<IActionResult> ListAccomodations()
        {
            var applicationUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var manager = _context.Managers.Where(x => x.ApplicationUser.Id == applicationUserId).First();

            
            var accomodations = _context.Accomodations.Where(p => p.ManagerId == manager.ManagerId)
                                .Include(x => x.AccomodationImages);

            return View(await accomodations.ToListAsync());
        }
       
        public async Task<IActionResult> ListEmployees()
        {
            var applicationUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var manager = _context.Managers.Where(x => x.ApplicationUser.Id == applicationUserId).First();

            var employees = _context.Employees.Where(p => p.ManagerId == manager.ManagerId)
                            .Include(x => x.ApplicationUser);

            return View(await employees.ToListAsync());
        }

        public IActionResult EmployeeToAccomodation()
        {
            var applicationUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var manager = _context.Managers.Where(x => x.ApplicationUser.Id == applicationUserId).First();
            var accomodations = _context.Accomodations.Where(p => p.ManagerId == manager.ManagerId).ToList();

            ViewData["AccomodationId"] = new SelectList(accomodations, "AccomodationId", "Name");


            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EmployeeToAccomodation(int? id,[Bind("AccomodationId")] Accomodation accomodation)
        {

            // se o id nao for passado
            if (id == null)
                return RedirectToAction(nameof(ListEmployees));

            var acc = _context.Accomodations.Where(i => i.AccomodationId == accomodation.AccomodationId).First();

            // se nao existir alojamentos com um certo id
            if(acc == null)
                return RedirectToAction(nameof(ListEmployees));

            // caso contrario, damos update ao EmployeeId do Accomodations
            acc.EmployeeId = (int)id;

            // ver se este alojamento tem algum booking e se tiver e o booking.employeeId estiver a nulo
            // usa-se o employee que esta a ser atribuido
            var booking = _context.Bookings.Where(b => b.AccomodationId == accomodation.AccomodationId);
            foreach(var i in booking)
            {
                if (i.EmployeeId == null)
                    i.EmployeeId = acc.EmployeeId;
            }

            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(ListEmployees));
        }


        public IActionResult RemoveAccomodationFromEmployee()
        {
            var applicationUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var manager = _context.Managers.Where(x => x.ApplicationUser.Id == applicationUserId).First();
            var accomodations = _context.Accomodations.Where(p => p.ManagerId == manager.ManagerId);

            ViewData["AccomodationId"] = new SelectList(accomodations, "AccomodationId", "Name");


            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> RemoveAccomodationFromEmployee(int? id,[Bind("AccomodationId")] Accomodation accomodation)
        {

            // se o id nao for passado
            if (id == null)
                return RedirectToAction(nameof(ListEmployees));

            var acc = _context.Accomodations.Where(i => i.AccomodationId == id).First();

            // se nao existir alojamentos com um certo id
            if(acc == null)
                return RedirectToAction(nameof(ListEmployees));

            // caso contrario, metemos o EmployeeId a null
            acc.EmployeeId = null;
            
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(ListEmployees));
        }

        // GET: Managers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var manager = await _context.Managers
                .FirstOrDefaultAsync(m => m.ManagerId == id);
            if (manager == null)
            {
                return NotFound();
            }

            return View(manager);
        }

        // POST: Managers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            // pesquisar na tabela de Managers o ApplicationUserId e remove esse manager
            var app = _context.Managers.Where(x => x.ManagerId == id).Include(x => x.ApplicationUser).First();
            var appuser = app.ApplicationUser;
            await _userManager.DeleteAsync(appuser);

            var manager = await _context.Managers.FindAsync(id);
            _context.Managers.Remove(manager);
            await _context.SaveChangesAsync();
            return RedirectToAction("ListManagers", "Admin");
        }
    }
}

HabitAqui/HabitAqui/Views/Admin/ListCustomers.cshtml
@model IEnumerable<HabitAqui.Models.Customer>

@{
    ViewData["Title"] = "List of Customers";
}

<h1>List of Customers</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                First Name
            </th>
            <th>
                Last Name
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @item.ApplicationUser.FirstName
            </td>
            <td>
                @item.ApplicationUser.LastName
            </td>
            <td>
                <a class="mx-1 btn btn-primary text-center" asp-action="Details" asp-controller="Customer" asp-route-id="@item.CustomerId">Details</a>
                <a class="mx-1 btn btn-danger text-center" asp-action="Delete" asp-controller="Customer" asp-route-id="@item.CustomerId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

HabitAqui/HabitAqui/Views/Admin/ListManagers.cshtml
@model IEnumerable<HabitAqui.Models.Manager>

@{
    ViewData["Title"] = "List of Managers";
}

<h1>List of Managers</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                First Name
            </th>
            <th>
                Last Name
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @item.ApplicationUser.FirstName
            </td>
            <td>
                @item.ApplicationUser.LastName
            </td>
            <td>
                <a class="mx-1 btn btn-primary text-center" asp-action="ManagerDetails" asp-route-id="@item.ManagerId">Details</a>
                <a class="mx-1 btn btn-danger text-center" asp-action="Delete" asp-controller="Manager" asp-route-id="@item.ManagerId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

HabitAqui/HabitAqui/Views/Admin/ManagerDetails.cshtml
@model HabitAqui.Models.Manager

@{
    ViewData["Title"] = "Manager Details";
}

<h2>@Model.ApplicationUser.FirstName @Model.ApplicationUser.LastName</h2>

<hr />
    
<h3>List of Accommodations</h3>
<table class="table">
    <thead>
        <tr>
            <th>
                Accomodation Id
            </th>
            <th>
                Accomodation Name
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Accomodations)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.AccomodationId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
            </tr>
        }
    </tbody>
</table>

<h3>List of Employees</h3>
<table class="table">
    <thead>
        <tr>
            <th>
                Employee Id
            </th>
            <th>
                Employee Name
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Employees)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.EmployeeId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
            </tr>
        }
    </tbody>
</table>
<a class="mx-1 btn btn-secondary text-center" asp-action="ListManagers">Back to List</a>