HabitAqui/HabitAqui/Controllers/BookingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HabitAqui.Data;
using HabitAqui.Models;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;

namespace HabitAqui.Controllers
{
    [Authorize(Roles = "Admin,Customer,Employee")]
    public class BookingsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public BookingsController(ApplicationDbContext context)
        {
            _context = context;
        }


        // GET: Bookings
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Bookings.Include(b => b.Accomodation);
            return View(await applicationDbContext.ToListAsync());
        }



        // GET: Bookings/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var booking = await _context.Bookings
                .Include(b => b.Accomodation)
                .FirstOrDefaultAsync(m => m.BookingId == id);
            if (booking == null)
            {
                return NotFound();
            }

            return View(booking);
        }

        // GET: Bookings/Create
        public IActionResult Create()
        {
            ViewData["AccomodationId"] = new SelectList(_context.Accomodations, "AccomodationId", "Description");
            return View();
        }

        // POST: Bookings/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("BookingId,BookingFrom,BookingUntil,AccomodationId")] Booking booking)
        {
            if (ModelState.IsValid)
            {

                _context.Add(booking);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["AccomodationId"] = new SelectList(_context.Accomodations, "AccomodationId", "Description", booking.AccomodationId);
            return View(booking);
        }

        // GET: Bookings/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var booking = await _context.Bookings.FindAsync(id);
            if (booking == null)
            {
                return NotFound();
            }
            ViewData["AccomodationId"] = new SelectList(_context.Accomodations, "AccomodationId", "Name", booking.AccomodationId);
            return View(booking);
        }

        // POST: Bookings/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("BookingId,BookingFrom,BookingUntil,AccomodationId")] Booking booking)
        {
            if (id != booking.BookingId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(booking);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BookingExists(booking.BookingId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["AccomodationId"] = new SelectList(_context.Accomodations, "AccomodationId", "Name", booking.AccomodationId);
            return View(booking);
        }

        [Authorize(Roles = "Admin,Employee,Customer")]
        // GET: Bookings/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var booking = await _context.Bookings
                .Include(b => b.Accomodation)
                .FirstOrDefaultAsync(m => m.BookingId == id);
            if (booking == null)
            {
                return NotFound();
            }

            return View(booking);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin,Employee,Customer")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var applicationUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var customer = _context.Customers.Where(x => x.ApplicationUser.Id == applicationUserId).FirstOrDefault();

            var booking = await _context.Bookings.FindAsync(id);
            _context.Bookings.Remove(booking);
            await _context.SaveChangesAsync();

            if (customer != null)
                return RedirectToAction("ListBookings", "Customer");
            else
                return RedirectToAction("ManageBookings","Employees");
        }

        private bool BookingExists(int id)
        {
            return _context.Bookings.Any(e => e.BookingId == id);
        }


        [Authorize(Roles = "Customer")]
        public IActionResult CreateFromDetails()
        {
            ViewData["AccomodationId"] = new SelectList(_context.Accomodations, "AccomodationId", "Description");
            return View();
        }

        [Authorize(Roles = "Customer")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateFromDetails(int id, [Bind("BookingId,BookingFrom,BookingUntil,AccomodationId")] Booking booking)
        {
            

            ViewData["AccomodationId"] = new SelectList(_context.Accomodations, "AccomodationId", "Description", booking.AccomodationId);

            var applicationUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var customer = _context.Customers.Where(x => x.ApplicationUser.Id == applicationUserId).First();
            

            booking.AccomodationId = id;
            booking.CustomerId = customer.CustomerId;

            // ver qual é o empregado responsavel pelo alojamento e atribuir esse id ao booking.EmployeeId
            // se nao for nenhum fica a null, se existir, o booking.Employee.EmployeeId = acc.EmployeeId
            var acc = _context.Accomodations.Where(p => p.AccomodationId == booking.AccomodationId).FirstOrDefault();
            if (acc.EmployeeId != null)
                booking.EmployeeId = (int)acc.EmployeeId;


            // verifica se a reserva é ou nao válida
            if (IsValidReservation(booking))
            {
                _context.Add(booking);
                await _context.SaveChangesAsync();
                return RedirectToAction("ListBookings","Customer");
            }

            return View("ErrorTest");
            
        }


        private bool IsValidReservation(Booking booking)
        {

            var accomodation_result = _context.Accomodations.Where(x => x.AccomodationId == booking.AccomodationId).First();
            var list_of_reservations = _context.Bookings.Where(x => x.AccomodationId == booking.AccomodationId);
            int counter = 0;


            var from = DateTime.Compare(accomodation_result.AvailableFrom,booking.BookingFrom);
            var until = DateTime.Compare(accomodation_result.AvailableUntil, booking.BookingUntil);

            /*Está dentro dos limites*/
            if (from <= 0 && until >= 0)
            {
                /*Verificar se já existe essa reserva e se reserva é valida*/

                foreach (var last_checkout in list_of_reservations)
                {
                    /*Verifica se a data escolhida "até" é superior à data escolhida "desde"*/
                    if (DateTime.Compare(booking.BookingUntil, booking.BookingFrom) > 0)
                    {
                        /*Se data escolhida "desde"  < data da reserva atual "até" e data escolhida "até" > data da reserva atual "desde" é porque não é válida*/
                        if (DateTime.Compare(booking.BookingFrom, last_checkout.BookingUntil) < 0 && DateTime.Compare(booking.BookingUntil, last_checkout.BookingFrom) > 0)
                        {
                            /* 
                             * caso de erro 
                             */
                            break;
                        }
                        counter++;
                    }
                }
            }

            if (list_of_reservations.Count() == counter)
                return true;

            return false;
        }
    }
}

HabitAqui/HabitAqui/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HabitAqui.Data;
using HabitAqui.Models;
using Microsoft.AspNetCore.Authorization;


namespace HabitAqui.Controllers
{
    [Authorize (Roles = "Admin")]
    public class CategoriesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CategoriesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Categories
        public async Task<IActionResult> Index()
        {
            return View(await _context.Categories.ToListAsync());
        }

        // GET: Categories/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Categories
                .FirstOrDefaultAsync(m => m.CategoryId == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // GET: Categories/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Categories/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CategoryId,Name")] Category category)
        {
            if (ModelState.IsValid)
            {
                _context.Add(category);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        // GET: Categories/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Categories.FindAsync(id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }

        // POST: Categories/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CategoryId,Name")] Category category)
        {
            if (id != category.CategoryId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(category);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CategoryExists(category.CategoryId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        // GET: Categories/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Categories
                .FirstOrDefaultAsync(m => m.CategoryId == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // POST: Categories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var category = await _context.Categories.FindAsync(id);
            _context.Categories.Remove(category);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CategoryExists(int id)
        {
            return _context.Categories.Any(e => e.CategoryId == id);
        }
    }
}

HabitAqui/HabitAqui/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>HabitAqui: @ViewData["Title"]</title>
    <link rel="stylesheet" href="~/css/bootswatchTheme.css" />
    @*     <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    *@
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header class="bg-dark">
        <nav class="navbar navbar-expand-sm navbar-light border-bottom box-shadow mb-3 navbar-expand-lg bg-primary" data-bs-theme="dark">
            <div class="container d-flex flex-row justify-content-between container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">HabitAqui</a>

                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between" id="navbarColor01">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Accomodation" asp-action="Index">Catalogue</a>
                        </li>
                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Categories" asp-action="Index">Categories</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Bookings" asp-action="Index">Reservations</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Admin" asp-action="ListManagers">List Managers</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Admin" asp-action="ListCustomers">List Customers</a>
                            </li>
                        }
                        @if (User.IsInRole("Customer"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Customer" asp-action="ListBookings">My Reservations</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Customer" asp-action="ListRatings">My Ratings</a>
                            </li>
                        }
                        @if (User.IsInRole("Manager"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Manager" asp-action="ListAccomodations">My Accomodations</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Manager" asp-action="ListEmployees">My Employees</a>
                            </li>
                        }
                        @if (User.IsInRole("Employee"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Employees" asp-action="ManageBookings">Manage Bookings</a>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted bg-primary">
        <div class="container container-fluid">
            &copy; 2023 airbnb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>