HabitAqui/HabitAqui/Models/Customer.cs
using Microsoft.AspNetCore.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HabitAqui.Models
{
    public class Customer
    {
        public int CustomerId {get; set;}

        public string Name { get; set; }
        public ICollection<AccomodationRating> AccomodationRatings { get; set; }
        public ICollection<Booking> Bookings { get; set; }
        public ApplicationUser ApplicationUser { get; set; }
    }
}

HabitAqui/HabitAqui/Models/CustomerViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HabitAqui.Models
{
    public class CustomerViewModel
    {
        public IQueryable<Booking> Bookings { get; set; }
        public IQueryable<AccomodationRating> AccomodationRatings { get; set; }
        public Customer Customer { get; set; }
    }
}

HabitAqui/HabitAqui/Controllers/AccomodationController.cs
using HabitAqui.Data;
using HabitAqui.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace HabitAqui.Controllers
{
    public class AccomodationController : Controller
    {
        private readonly ApplicationDbContext _context;

        public AccomodationController(ApplicationDbContext context)
        {
            _context = context;
        }

        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var accomodation = _context.Accomodations.Include(x => x.AccomodationImages);
            return View(await accomodation.ToListAsync());
        }

        [AllowAnonymous]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var accomodation = await _context.Accomodations
                .Include(e => e.Category)
                .Include(x => x.AccomodationImages)
                .Include(y => y.AccomodationRatings).ThenInclude(c => c.Customer)
                .FirstOrDefaultAsync(m => m.AccomodationId == id);
            if (accomodation == null)
            {
                return NotFound();
            }

            return View(accomodation);
        }
        

        [Authorize(Roles = "Admin, Manager")]
        // GET: Accomodation/Create
        public IActionResult Create()
        {
            ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "Name");
            return View();
        }

        // POST: Accomodation/Create
        [Authorize(Roles = "Admin, Manager")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("AccomodationId,Name,Description,Location,AvailableFrom,AvailableUntil,PricePerNight,CategoryId")] Accomodation accomodation, List<IFormFile> files)
        {
            // atribui alojamento a um manager
            var applicationUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var manager = _context.Managers.Where(x => x.ApplicationUser.Id == applicationUserId).First();
            accomodation.ManagerId = manager.ManagerId;


            if (ModelState.IsValid)
            {
                
                _context.Add(accomodation);

                foreach (var file in files)
                {
                    var fileName = Path.GetFileNameWithoutExtension(file.FileName);
                    var extension = Path.GetExtension(file.FileName);
                    var fileModel = new AccomodationImage
                    {
                        Accomodation = accomodation,
                        CreatedOn = DateTime.UtcNow,
                        FileType = file.ContentType,
                        Extension = extension,
                        Name = fileName,
                    };
                    using (var dataStream = new MemoryStream())
                    {
                        await file.CopyToAsync(dataStream);
                        fileModel.Data = dataStream.ToArray();
                    }
                    _context.AccomodationImages.Add(fileModel);
                }
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }



            ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "Name", accomodation.CategoryId);

            return View(accomodation);
        }

        [Authorize(Roles = "Admin, Manager")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var accomodation = await _context.Accomodations.FindAsync(id);
            if (accomodation == null)
            {
                return NotFound();
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "Name", accomodation.CategoryId);
            return View(accomodation);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin, Manager")]
        public async Task<IActionResult> Edit(int id, [Bind("AccomodationId,Name,Description,Location,AvailableFrom,AvailableUntil,PricePerNight,CategoryId,ManagerId")] Accomodation accomodation, List<IFormFile> files)
        {
            if (id != accomodation.AccomodationId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {

                    foreach (var file in files)
                    {
                        var fileName = Path.GetFileNameWithoutExtension(file.FileName);
                        var extension = Path.GetExtension(file.FileName);
                        var fileModel = new AccomodationImage
                        {
                            Accomodation = accomodation,
                            CreatedOn = DateTime.UtcNow,
                            FileType = file.ContentType,
                            Extension = extension,
                            Name = fileName,
                        };
                        using (var dataStream = new MemoryStream())
                        {
                            await file.CopyToAsync(dataStream);
                            fileModel.Data = dataStream.ToArray();
                        }
                        _context.AccomodationImages.Add(fileModel);
                    }

                    _context.Update(accomodation);
                    await _context.SaveChangesAsync();
                    
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AccomodationExists(accomodation.AccomodationId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "Name", accomodation.CategoryId);
            return View(accomodation);
        }


        [Authorize(Roles = "Admin, Manager")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var accomodation = await _context.Accomodations
                .Include(p => p.Category)
                .FirstOrDefaultAsync(m => m.AccomodationId == id);
            if (accomodation == null)
            {
                return NotFound();
            }

            return View(accomodation);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin, Manager")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var accomodation = await _context.Accomodations.FindAsync(id);
            _context.Accomodations.Remove(accomodation);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        // checks if accomodation exists in db
        private bool AccomodationExists(int id)
        {
            return _context.Accomodations.Any(e => e.AccomodationId == id);
        }

    }
}

HabitAqui/HabitAqui/Controllers/BookingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HabitAqui.Data;
using HabitAqui.Models;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;

namespace HabitAqui.Controllers
{
    [Authorize(Roles = "Admin,Customer,Employee")]
    public class BookingsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public BookingsController(ApplicationDbContext context)
        {
            _context = context;
        }


        // GET: Bookings
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Bookings.Include(b => b.Accomodation);
            return View(await applicationDbContext.ToListAsync());
        }



        // GET: Bookings/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var booking = await _context.Bookings
                .Include(b => b.Accomodation)
                .FirstOrDefaultAsync(m => m.BookingId == id);
            if (booking == null)
            {
                return NotFound();
            }

            return View(booking);
        }

        // GET: Bookings/Create
        public IActionResult Create()
        {
            ViewData["AccomodationId"] = new SelectList(_context.Accomodations, "AccomodationId", "Description");
            return View();
        }

        // POST: Bookings/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("BookingId,BookingFrom,BookingUntil,AccomodationId")] Booking booking)
        {
            if (ModelState.IsValid)
            {

                _context.Add(booking);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["AccomodationId"] = new SelectList(_context.Accomodations, "AccomodationId", "Description", booking.AccomodationId);
            return View(booking);
        }

        // GET: Bookings/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var booking = await _context.Bookings.FindAsync(id);
            if (booking == null)
            {
                return NotFound();
            }
            ViewData["AccomodationId"] = new SelectList(_context.Accomodations, "AccomodationId", "Name", booking.AccomodationId);
            return View(booking);
        }

        // POST: Bookings/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("BookingId,BookingFrom,BookingUntil,AccomodationId")] Booking booking)
        {
            if (id != booking.BookingId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(booking);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BookingExists(booking.BookingId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["AccomodationId"] = new SelectList(_context.Accomodations, "AccomodationId", "Name", booking.AccomodationId);
            return View(booking);
        }

        [Authorize(Roles = "Admin,Employee,Customer")]
        // GET: Bookings/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var booking = await _context.Bookings
                .Include(b => b.Accomodation)
                .FirstOrDefaultAsync(m => m.BookingId == id);
            if (booking == null)
            {
                return NotFound();
            }

            return View(booking);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin,Employee,Customer")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var applicationUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var customer = _context.Customers.Where(x => x.ApplicationUser.Id == applicationUserId).FirstOrDefault();

            var booking = await _context.Bookings.FindAsync(id);
            _context.Bookings.Remove(booking);
            await _context.SaveChangesAsync();

            if (customer != null)
                return RedirectToAction("ListBookings", "Customer");
            else
                return RedirectToAction("ManageBookings","Employees");
        }

        private bool BookingExists(int id)
        {
            return _context.Bookings.Any(e => e.BookingId == id);
        }


        [Authorize(Roles = "Customer")]
        public IActionResult CreateFromDetails()
        {
            ViewData["AccomodationId"] = new SelectList(_context.Accomodations, "AccomodationId", "Description");
            return View();
        }

        [Authorize(Roles = "Customer")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateFromDetails(int id, [Bind("BookingId,BookingFrom,BookingUntil,AccomodationId")] Booking booking)
        {
            

            ViewData["AccomodationId"] = new SelectList(_context.Accomodations, "AccomodationId", "Description", booking.AccomodationId);

            var applicationUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var customer = _context.Customers.Where(x => x.ApplicationUser.Id == applicationUserId).First();
            

            booking.AccomodationId = id;
            booking.CustomerId = customer.CustomerId;

            // ver qual é o empregado responsavel pelo alojamento e atribuir esse id ao booking.EmployeeId
            // se nao for nenhum fica a null, se existir, o booking.Employee.EmployeeId = acc.EmployeeId
            var acc = _context.Accomodations.Where(p => p.AccomodationId == booking.AccomodationId).FirstOrDefault();
            if (acc.EmployeeId != null)
                booking.EmployeeId = (int)acc.EmployeeId;


            // verifica se a reserva é ou nao válida
            if (IsValidReservation(booking))
            {
                _context.Add(booking);
                await _context.SaveChangesAsync();
                return RedirectToAction("ListBookings","Customer");
            }

            return View("ErrorTest");
            
        }


        private bool IsValidReservation(Booking booking)
        {

            var accomodation_result = _context.Accomodations.Where(x => x.AccomodationId == booking.AccomodationId).First();
            var list_of_reservations = _context.Bookings.Where(x => x.AccomodationId == booking.AccomodationId);
            int counter = 0;


            var from = DateTime.Compare(accomodation_result.AvailableFrom,booking.BookingFrom);
            var until = DateTime.Compare(accomodation_result.AvailableUntil, booking.BookingUntil);

            /*Está dentro dos limites*/
            if (from <= 0 && until >= 0)
            {
                /*Verificar se já existe essa reserva e se reserva é valida*/

                foreach (var last_checkout in list_of_reservations)
                {
                    /*Verifica se a data escolhida "até" é superior à data escolhida "desde"*/
                    if (DateTime.Compare(booking.BookingUntil, booking.BookingFrom) > 0)
                    {
                        /*Se data escolhida "desde"  < data da reserva atual "até" e data escolhida "até" > data da reserva atual "desde" é porque não é válida*/
                        if (DateTime.Compare(booking.BookingFrom, last_checkout.BookingUntil) < 0 && DateTime.Compare(booking.BookingUntil, last_checkout.BookingFrom) > 0)
                        {
                            /* 
                             * caso de erro 
                             */
                            break;
                        }
                        counter++;
                    }
                }
            }

            if (list_of_reservations.Count() == counter)
                return true;

            return false;
        }
    }
}

HabitAqui/HabitAqui/Views/Customer/Delete.cshtml
@model HabitAqui.Models.Customer

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Customer</h4>
    <hr />
    <dl class="row">
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="CustomerId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

HabitAqui/HabitAqui/Views/Customer/Details.cshtml
@model HabitAqui.Models.CustomerViewModel

@{
    ViewData["Title"] = Model.Customer.ApplicationUser.FirstName + " " +  Model.Customer.ApplicationUser.LastName;
}

<h2>@Model.Customer.ApplicationUser.FirstName @Model.Customer.ApplicationUser.LastName</h2>

<hr/>

<h3>Bookings</h3>
<table class="table">
    <thead>
        <tr>
            <th>
                From
            </th>
            <th>
                Until
            </th>
            <th>
                Status
            </th>
            <th>
                Accomodation Name
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Bookings)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.BookingFrom)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.BookingUntil)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Status)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Accomodation.Name)
                </td>
            </tr>
        }
    </tbody>
</table>

<h3>Ratings</h3>

<table class="table">
    <thead>
        <tr>
            <th>
                Accomodation Id
            </th>
            <th>
                Comment
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.AccomodationRatings)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.AccomodationId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Comment)
            </td>
        </tr>
        }
    </tbody>
</table>

<div>
    <a class="mx-1 btn btn-secondary text-center" asp-controller="Admin" asp-action="ListCustomers">Back to List</a>
</div>

HabitAqui/HabitAqui/Views/Customer/ListBookings.cshtml
@model List<HabitAqui.Models.Booking>

@{
    ViewData["Title"] = "My Reservations";
}

<h1>My Reservations</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                Accomodation
            </th>
            <th>
                From
            </th>
            <th>
                Until
            </th>
            <th>
                Reservation Status
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>

        @foreach (var item in Model)
        {
        <tr>
            <td>
                <a asp-controller="Accomodation" asp-action="Details" asp-route-id="@item.AccomodationId">@item.AccomodationId</a>
            </td>
            <td>
                @Html.DisplayFor(a => item.BookingFrom)
            </td>
            <td>
                @Html.DisplayFor(a => item.BookingUntil)
            </td>
            <td>
                @Html.DisplayFor(a => item.Status)
            </td>
            <td>
                <a class="btn btn-danger" asp-action="Delete" asp-controller="Bookings" asp-route-id="@item.BookingId">Cancel</a>
            </td>
        </tr>
        }
    </tbody>
</table>

HabitAqui/HabitAqui/Views/Customer/ListRatings.cshtml
@model List<HabitAqui.Models.AccomodationRating>

@{
    ViewData["Title"] = "My Ratings";
}

<h1>My Ratings</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                Accomodation
            </th>
            <th>
                Comment
            </th>
            <th>
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>

        @foreach (var item in Model)
        {
        <tr>
            <td>
                <a asp-controller="Accomodation" asp-action="Details" asp-route-id="@item.AccomodationId">@item.AccomodationId</a>
            </td>
            <td>
                @Html.DisplayFor(a => item.Comment)
            </td>
            <td>
                <a class="btn btn-danger" asp-action="Delete" asp-controller="AccomodationRatings" asp-route-id="@item.AccomodationRatingId">Delete</a>
            </td>
        </tr>

        }
    </tbody>
</table>